version: '3.8'

services:
  frontend:
    build: .
    container_name: hotel-frontend
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3000
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules


networks:
  default:
    external: true
    name: room-reservation_hotel-network 